version: '2.3'
services:
  ####################
  ###   MongoDB
  ####################
  mongo:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ROOT_USER=user
      - MONGODB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"